// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_rendstep_stencil[] =
"<?xml version=\"1.0\"?>"
"<!-- stencil.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.renderloop.step.shadow.stencil</name>"
"        <implementation>csStencilShadowLoader</implementation>"
"        <description>stencil shadow render loop step</description>"
"        <requires>"
"          <class>crystalspace.graphics3d.</class>"
"	  <class>crystalspace.graphics3d.shadermanager</class>"
"        </requires>"
"      </class>"
"      <class>"
"        <name>crystalspace.renderloop.step.shadow.stencil.type</name>"
"        <implementation>csStencilShadowType</implementation>"
"        <description>stencil shadow render loop step type</description>"
"        <requires>"
"          <class>crystalspace.graphics3d.</class>"
"	  <class>crystalspace.graphics3d.shadermanager</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csStencilShadowLoader_FACTORY_REGISTER_DEFINED 
  #define csStencilShadowLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csStencilShadowLoader) 
  #endif
  #ifndef csStencilShadowType_FACTORY_REGISTER_DEFINED 
  #define csStencilShadowType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csStencilShadowType) 
  #endif

class rendstep_stencil
{
SCF_REGISTER_STATIC_LIBRARY(rendstep_stencil,metainfo_rendstep_stencil)
  #ifndef csStencilShadowLoader_FACTORY_REGISTERED 
  #define csStencilShadowLoader_FACTORY_REGISTERED 
    csStencilShadowLoader_StaticInit csStencilShadowLoader_static_init__; 
  #endif
  #ifndef csStencilShadowType_FACTORY_REGISTERED 
  #define csStencilShadowType_FACTORY_REGISTERED 
    csStencilShadowType_StaticInit csStencilShadowType_static_init__; 
  #endif
public:
 rendstep_stencil();
};
rendstep_stencil::rendstep_stencil() {}

}
