// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_rendstep_stencil2[] =
"<?xml version=\"1.0\"?>"
"<!-- stencil2.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.renderloop.step.shadow.stencil2</name>"
"        <implementation>csStencil2ShadowLoader</implementation>"
"        <description>stencil shadow render loop step</description>"
"        <requires>"
"          <class>crystalspace.graphics3d.</class>"
"	  <class>crystalspace.graphics3d.shadermanager</class>"
"        </requires>"
"      </class>"
"      <class>"
"        <name>crystalspace.renderloop.step.shadow.stencil2.type</name>"
"        <implementation>csStencil2ShadowType</implementation>"
"        <description>stencil shadow render loop step type</description>"
"        <requires>"
"          <class>crystalspace.graphics3d.</class>"
"	  <class>crystalspace.graphics3d.shadermanager</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef csStencil2ShadowLoader_FACTORY_REGISTER_DEFINED 
  #define csStencil2ShadowLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csStencil2ShadowLoader) 
  #endif
  #ifndef csStencil2ShadowType_FACTORY_REGISTER_DEFINED 
  #define csStencil2ShadowType_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(csStencil2ShadowType) 
  #endif

class rendstep_stencil2
{
SCF_REGISTER_STATIC_LIBRARY(rendstep_stencil2,metainfo_rendstep_stencil2)
  #ifndef csStencil2ShadowLoader_FACTORY_REGISTERED 
  #define csStencil2ShadowLoader_FACTORY_REGISTERED 
    csStencil2ShadowLoader_StaticInit csStencil2ShadowLoader_static_init__; 
  #endif
  #ifndef csStencil2ShadowType_FACTORY_REGISTERED 
  #define csStencil2ShadowType_FACTORY_REGISTERED 
    csStencil2ShadowType_StaticInit csStencil2ShadowType_static_init__; 
  #endif
public:
 rendstep_stencil2();
};
rendstep_stencil2::rendstep_stencil2() {}

}
